{% set name = "django-typed-models" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-typed-models-{{ version }}.tar.gz
  sha256: 0fe393dcc9e219024bf7fdc23cb9f3fafe1311dcd8fcf3f156bb97410d1f99e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django
    - setuptools

test:
  imports:
    - typedmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/craigds/django-typed-models
  summary: Sane single table model inheritance for Django
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
