{% set version = "0.10.0" %}

package:
  name: django-typed-models
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-typed-models/django-typed-models-{{ version }}.tar.gz
  sha256: 0682c87e5887124d4990f851d73e172103828e8b48ad2ce53ae039b1498cedb6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - django

test:
  imports:
    - typedmodels

about:
  home: http://github.com/craigds/django-typed-models
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Sane single table model inheritance for Django.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
