{% set version = "0.9.0" %}

package:
  name: django-typed-models
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-typed-models/django-typed-models-{{ version }}.tar.gz
  sha256: 39723d0476a1b058fae45806a5b8b5bccd21de7236d4f8b8bbcad4ccb5330fad

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - django

test:
  imports:
    - typedmodels

about:
  home: http://github.com/craigds/django-typed-models
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Sane single table model inheritance for Django.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
