{% set name = "django-typed-models" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-typed-models-{{ version }}.tar.gz
  sha256: cd1772c810e79ab170d3b39804662e0c9516b21df7bd4eade84801e93ca32f78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django
    - setuptools

test:
  imports:
    - typedmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/craigds/django-typed-models
  summary: Sane single table model inheritance for Django
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
