{% set version = "0.11.0" %}

package:
  name: django-typed-models
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-typed-models/django-typed-models-{{ version }}.tar.gz
  sha256: ca436bed4c0d886f78cd0085ec97aa05f81cd8f2e699e738a05d3f2676a13302

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - django

test:
  imports:
    - typedmodels

about:
  home: http://github.com/craigds/django-typed-models
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Sane single table model inheritance for Django.

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
