schema_version: 1

context:
  version: "0.16.0"

package:
  name: django-typed-models
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/django-typed-models/django_typed_models-${{ version }}.tar.gz
  sha256: 53a2250748034a38843ad98db9a122890f8a6069ba7c0d6a2c920a3801ee282e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=5.2
    - django-stubs-ext
    - typing_extensions

tests:
  - python:
      imports:
        - typedmodels
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Sane single table model inheritance for Django
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/craigds/django-typed-models

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
