# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "URryv2Dvn3xR0CSH8h4A8ukw08O57KY9gM39/qIzNsOdgprVwdXvFb8kcbArP5R+xT/Cmz8yaipXcz+eRKTlseytCSuhjYRbIXrVx2nAt/cH1r/aM4BgiaT/Eh8etlMwlQfvfziB3ejqZ/+g9bzRqMg1bRiFYaPGDScLCOdzdCJ8r5L16PF4T7yycyuk6hpuV7hRq+dxPN3YPIWMtq6TBbm4E45jyMX+TAGOGj81BcjaKRRjZi5MBtz5Ul7K8Dyvadu3KrE0Wlof5tP3bpHM/3bjLBWpNsK4kGcX1mAr6HgmF8vKLmeCnu5SeMwXFUc+KEnymaSln1P+GDrPBBnb1hbVN768IUOOaOTS/mIemvxBqqgdxdAMmKhvJPHxwVg2CmCupoRxHjJlRUneFbo10KNHkigYCxY1QdKb9THnmmhMOVH4nPpVK+PobzPBtUTvzCwl5XbE9DvgEax1mAbklscK9U8zgsnLaWdGGkniu86vkK+CtSFGKnMLOceqx0u0x8nR2zlIkpCmjEeiVh8qCol44TCrFPQROA7zobNUZGCpz96ZDfc7qclghlXQAAbn24WagwAwAqWnbGJLO5YJbuVSF+Dehg4qiK3jgbbFctlp/GiToFFa4CHnGvGTQ9N/a6SMEUPUVhyZjMnIQ6MSweNGvOfFdWugD8yZdXAjUzQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
