travis:
  secure:
    BINSTAR_TOKEN: OXKr7GeMZucGJLCo2St/NK/pDxpkJsNY3nptTaMNuY3Srkhvt47cPFVW1Ge+Z9700+kxF4/s9iRetrmORdUMQDkSOSl++63Kya2xnb2V9i+6dS+FeUtTJDPyE438zm2wTBICsTh/fx5fvIRto1pbYozsf/VbWzHIUejI+kqdKfxTQX42Q8vB8hQA2bhwodma7PLfNCaVu48HP5sTQiFZHYYVmcWYGfkwoCXlSY9lMS+fCC93OyvUludyQMGZ/gAn4YecOGFTzsNm3ybfAh1O2lxfuSulpYGANelah7t3u6Ou2LlU3RFLYYChRfV0faE7AMivwNllYHz+cmPUssib6QfI91glTP/Sg7YfBGppfxaTxuqDcj2BvsZZ8PxDtNHw/Uqoucj5ZDp7wrsmGwxW2jdluJtgjxJccj6KWFLGT18ihGrUyiaixGcov5d0KAkF/PVncEAkTefOxYxnLnKY6kxgQEcvuDOYbAsirV3GaJdKWHSHeAkteju8A+82BDKD/T5ckWF6ytyFYKSyP8q4os1+DZrn3dE2Z4pldS9R4khzgKwFQLyYMUmQ46ko36497LQCsHwGTcCEqcupFHjciSxPZteXXgAnvV++WaEC+pK3Pl7VIJMF4C3SQT8Yrv5gYj34qI87AxsPjtom90V51I8XqnYhJI5mT5eBqNzLQAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
